version: '3.7'

services:
  jdownloader2:
    image: ${IMAGE_NAME:-jaymoulin/jdownloader}:${IMAGE_TAG:-latest}
    networks:
      - jd2-net
    ports:
      - target: ${JD2_DATA_PORT}
        published: ${JD2_DATA_PORT}
        protocol: tcp
        mode: ${JD2_PORT_MODE}
      - target: ${JD2_DATA_PORT}
        published: ${JD2_DATA_PORT}
        protocol: udp
        mode: ${JD2_PORT_MODE}
    volumes:
      - data-vol:/root/Downloads
      - cfg-vol:/opt/JDownloader/cfg
      - update-vol:/opt/JDownloader/update
      - jd-vol:/opt/JDownloader/jd
      - libs-vol:/opt/JDownloader/libs
      - extensions-vol:/opt/JDownloader/extensions
      - tmp-vol:/opt/JDownloader/tmp
      - tools-vol:/opt/JDownloader/tools
      - translations-vol:/opt/JDownloader/translations
      - themes-vol:/opt/JDownloader/themes
      - licenses-vol:/opt/JDownloader/licenses
    deploy:
      mode: replicated
      replicas: ${JD2_REPLICAS:-1}
      restart_policy:
        delay: ${JD2_RESTART_POLICY_DELAY:-5s}
        window: ${JD2_RESTART_POLICY_WINDOW:-5m}
      resources:
        limits:
          cpus: '${JD2_LIMITS_CPUS:-1}'
          memory: ${JD2_LIMITS_MEMORY:-256M}
        reservations:
          cpus: '${JD2_RESERVATIONS_CPUS:-0.001}'
          memory: ${JD2_RESERVATIONS_MEMORY:-128M}

networks:
  jd2-net:
    name: ${JD2_NET_NAME:-jd2-net}
    driver: overlay
    attachable: ${JD2_NET_ATTACHABLE:-true}

volumes:
  data-vol:
    name: ${JD2_DATA_VOL_NAME:-jd2-data-vol}
    driver: local
    driver_opts:
      type: ${JD2_DATA_VOLUME_TYPE}
      o: ${JD2_DATA_VOLUME_OPTIONS}
      device: ${JD2_DATA_VOLUME_DEVICE}

  cfg-vol:
    name: ${JD2_CFG_VOL_NAME:-jd2-cfg-vol}
    driver: local
    driver_opts:
      type: ${JD2_CFG_VOLUME_TYPE}
      o: ${JD2_CFG_VOLUME_OPTIONS}
      device: ${JD2_CFG_VOLUME_DEVICE}

  update-vol:
    name: ${JD2_UPDATE_VOL_NAME:-jd2-update-vol}

  jd-vol:
    name: ${JD2_JD_VOL_NAME:-jd2-jd-vol}

  libs-vol:
    name: ${JD2_LIBS_VOL_NAME:-jd2-libs-vol}

  extensions-vol:
    name: ${JD2_EXTENSIONS_VOL_NAME:-jd2-extensions-vol}

  tmp-vol:
    name: ${JD2_TMP_VOL_NAME:-jd2-tmp-vol}

  tools-vol:
    name: ${JD2_TOOLS_VOL_NAME:-jd2-tools-vol}

  translations-vol:
    name: ${JD2_TRANSLATIONS_VOL_NAME:-jd2-translations-vol}

  themes-vol:
    name: ${JD2_THEMES_VOL_NAME:-jd2-themes-vol}

  licenses-vol:
    name: ${JD2_LICENSES_VOL_NAME:-jd2-licenses-vol}
