version: '2.4'

services:
  jdownloader2:
    image: jaymoulin/jdownloader:${IMAGE_TAG:-latest}
    container_name: ${JDOWNLOADER2_CONTAINER_NAME:-jdownloader2}
    volumes:
      - config-vol:/opt/JDownloader/cfg
      - data-vol:/root/Downloads
    restart: always
    mem_limit: ${JDOWNLOADER2_MEM_LIMIT:-256M}
    mem_reservation: ${JDOWNLOADER2_MEM_RESERVATION:-64M}

volumes:
  config-vol:
    name: ${JDOWNLOADER2_CONFIG_VOL_NAME:-jdownloader2-config-vol}

  data-vol:
    name: ${JDOWNLOADER2_DATA_VOL_NAME:-jdownloader2-data-vol}
    driver: local
    driver_opts:
      type: ${JDOWNLOADER2_DATA_VOLUME_TYPE}
      o: ${JDOWNLOADER2_DATA_VOLUME_OPTIONS}
      device: ${JDOWNLOADER2_DATA_VOLUME_DEVICE}
