version: '3.7'

services:
  jdownloader2:
    image: ${IMAGE_NAME:-jaymoulin/jdownloader}:${IMAGE_TAG:-latest}
    networks:
      jd2-net:
    ports:
      - target: ${DATA_PORT}
        published: ${DATA_PORT}
        protocol: tcp
        mode: ${PORT_MODE}
      - target: ${DATA_PORT}
        published: ${DATA_PORT}
        protocol: udp
        mode: ${PORT_MODE}
    volumes:
      - data-vol:/root/Downloads
      - cfg-vol:/opt/JDownloader/cfg
      - update-vol:/opt/JDownloader/update
      - jd-vol:/opt/JDownloader/jd
      - libs-vol:/opt/JDownloader/libs
      - extensions-vol:/opt/JDownloader/extensions
      - tmp-vol:/opt/JDownloader/tmp
      - tools-vol:/opt/JDownloader/tools
      - translations-vol:/opt/JDownloader/translations
      - themes-vol:/opt/JDownloader/themes
      - licenses-vol:/opt/JDownloader/licenses
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-1}
      restart_policy:
        delay: ${RESTART_DELAY:-5s}
      update_config:
        delay: ${UPDATE_DELAY:-1m}
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-1}'
          memory: ${RESOURCES_LIMITS_MEMORY:-256M}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-128M}

networks:
  jd2-net:
    name: ${JD2_NET_NAME:-jd2-net}
    driver: ${JD2_NET_DRIVER:-overlay}
    attachable: ${JD2_NET_ATTACHABLE:-true}

volumes:
  data-vol:
    name: ${DATA_VOL_NAME:-jd2-data-vol}
    driver: local
    driver_opts:
      type: ${DATA_VOL_TYPE}
      o: ${DATA_VOL_OPTIONS}
      device: ${DATA_VOL_DEVICE}

  cfg-vol:
    name: ${CFG_VOL_NAME:-jd2-cfg-vol}
    driver: local
    driver_opts:
      type: ${CFG_VOL_TYPE}
      o: ${CFG_VOL_OPTIONS}
      device: ${CFG_VOL_DEVICE}

  update-vol:
    name: ${UPDATE_VOL_NAME:-jd2-update-vol}

  jd-vol:
    name: ${JD_VOL_NAME:-jd2-jd-vol}

  libs-vol:
    name: ${LIBS_VOL_NAME:-jd2-libs-vol}

  extensions-vol:
    name: ${EXTENSIONS_VOL_NAME:-jd2-extensions-vol}

  tmp-vol:
    name: ${TMP_VOL_NAME:-jd2-tmp-vol}

  tools-vol:
    name: ${TOOLS_VOL_NAME:-jd2-tools-vol}

  translations-vol:
    name: ${TRANSLATIONS_VOL_NAME:-jd2-translations-vol}

  themes-vol:
    name: ${THEMES_VOL_NAME:-jd2-themes-vol}

  licenses-vol:
    name: ${LICENSES_VOL_NAME:-jd2-licenses-vol}
